### ISSUE TITLE
BWA has problems with cached ref files

### ISSUE THREAD

**Issue by sb10** [VertebrateResequencing/muxfys#2]
`[bwt_restore_sa] SA-BWT inconsistency: primary is not the same. Abort!`

Happens when (via wr) we have a mount like `Mounts:[{"Mount":"npg-repository","Targets":[{"Path":"npg-repository","CacheDir":"/tmp/mounts_cache"}]}`. The first bwa command to run works, but a subsequent one using the same cache fails.

**Comment by jidur** [comment]
An example command  (bwa version 0.7.16a-r1181)

bwa mem -t 16 -p -Y -K 100000000 ../npg-repository/references/Homo_sapiens/GRCh38_full_analysis_set_plus_decoy_hla/all/bwa0_6/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa /tmp/wr_cwd/a/5/3/30b339e6c799d224661392d36f106379582752/tmp/cf75PvSGKG/alntgt_bamtofastq_out

**Comment by jidur** [comment]
I also found a similar issue when using `Mounts:[{"Mount":"npg-repository","Targets":[{"Path":"npg-repository","Cache":true}]}`

**Comment by sb10** [comment]
Thanks, I can duplicate this for a cache dir at an absolute path. But I don't see how it can be possible with a unique cache dir. Can you provide more details on exactly what you did to arrive at a problem using just "Cache":true?

```
wr cloud deploy --os_ram 20000
[ssh to resulting node]

sudo apt-get update && sudo apt-get install make gcc zlib1g-dev -y
wget "https://github.com/lh3/bwa/releases/download/v0.7.16/bwa-0.7.16a.tar.bz2"
tar -xvjf bwa-0.7.16a.tar.bz2
cd bwa-0.7.16a
make
cd ..

/tmp/wr mount --mount_json '[{"Mount":"npg-repository","Targets":[{"Path":"npg-repository","CacheDir":"/tmp/mounts_cache"}]}]' -v &

curl -sS ftp://ftp.sra.ebi.ac.uk/vol1/fastq/SRR507/SRR507778/SRR507778_1.fastq.gz | gzip -d | head -100 > SRR507778_1.fastq
bwa-0.7.16a/bwa mem -t 16 -p -Y -K 100000000 npg-repository/references/Homo_sapiens/GRCh38_full_analysis_set_plus_decoy_hla/all/bwa0_6/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa SRR507778_1.fastq
```

This downloads (and caches) various reference index files, and then the bwa command completes successfully.

Repeating the bwa command also succeeds.

Remounting and repeating the command, however:

```
fg
ctrl-c
/tmp/wr mount --mount_json '[{"Mount":"npg-repository","Targets":[{"Path":"npg-repository","CacheDir":"/tmp/mounts_cache"}]}]' -v &
bwa-0.7.16a/bwa mem -t 16 -p -Y -K 100000000 npg-repository/references/Homo_sapiens/GRCh38_full_analysis_set_plus_decoy_hla/all/bwa0_6/Homo_sapiens.GRCh38_full_analysis_set_plus_decoy_hla.fa SRR507778_1.fastq
```

Does OpenFile/Seek calls on some of the reference index files and fails:

`[bwt_restore_sa] SA-BWT inconsistency: primary is not the same. Abort!`

As an initial guess, is this simply due to cached files getting touched on read?

**Comment by jidur** [comment]
I've just checked this now and it is the same bwa error `[bwt_restore_sa] SA-BWT inconsistency: primary is not the same. Abort!` that I get when using "Cache":true.

**Comment by sb10** [comment]
Still not sure about the problem with a unique cache dir, but hopefully the main issue with a shared cache dir is now fixed.
